### ISSUE TITLE
Where is the paper?

### ISSUE THREAD

**Issue by wizardk** [thuhcsi/PortableTTS#1]

**Comment by unrea1-sama** [comment]
This work is part of my paper for applying my master's degree and the paper will be published by Tsinghua University after I graduate.

**Comment by wizardk** [comment]
Got it. On more thing, have you compared PortableTTS with NaturalSpeech?

**Comment by unrea1-sama** [comment]
No. When I was writing my paper, there is no public implementation for NaturalSpeech. So I didn't reproduce NaturalSpeech in my experiment.
